### ISSUE TITLE
i got a bug with tablist plugin how can i fixed it?

### ISSUE THREAD

**Issue by CyprusCraft** [ElgarL/GroupManager#101]
[05:51:33] [Server thread/INFO]: [TabList] Enabling TabList v5.7.2
[05:51:34] [Server thread/INFO]: [TabList] Hooked PlaceholderAPI version: 2.11.3
[05:51:34] [Server thread/ERROR]: Error occurred while enabling TabList v5.7.2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.anjocaido.groupmanager.GroupManager.getWorldsHolder()" because "this.groupManager" is null
	at net.milkbowl.vault.permission.plugins.Permission_GroupManager.getGroups(Permission_GroupManager.java:337) ~[Vault.jar:?]
	at hu.montlikadani.tablist.utils.plugin.PermissionService.getGroups(PermissionService.java:79) ~[TabList-bukkit-v5.7.2.jar:?]
	at hu.montlikadani.tablist.tablist.groups.Groups.load(Groups.java:140) ~[TabList-bukkit-v5.7.2.jar:?]
	at hu.montlikadani.tablist.TabList.onEnable(TabList.java:107) ~[TabList-bukkit-v5.7.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-43]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-43]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-43]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:547) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-43]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[05:51:34] [Server thread/INFO]: [TabList] Disabling TabList v5.7.2

**Comment by ElgarL** [comment]
Don't use reload plugins like plugman in a production environment, they break things.

**Comment by CyprusCraft** [comment]
I dont use plugman or reload plugin

Στις Τρί 20 Ιουν 2023, 19:31 ο χρήστης ElgarL ***@***.***>
έγραψε:

**Comment by CyprusCraft** [comment]
The problem is with groupmanager , Tablist and Vault

Στις Τετ 21 Ιουν 2023, 07:59 ο χρήστης Stefanos Mixail <
***@***.***> έγραψε:

**Comment by CyprusCraft** [comment]
When i open the server tablist wont open because of groupmanager is null.

Στις Τετ 21 Ιουν 2023, 08:01 ο χρήστης Stefanos Mixail <
***@***.***> έγραψε:

**Comment by ElgarL** [comment]
Can you pastebin your servers latest.log (from startup)

**Comment by CyprusCraft** [comment]
Στις Τετ 21 Ιουν 2023, 12:04 ο χρήστης ElgarL ***@***.***>
έγραψε:

**Comment by aSethyy** [comment]
https://pastebin.com/ffq1X0Vh

Here is an error created by Tab. I have reached out by the owner of the tab plugin and he says it is an issue that must be resolved by Groupmanager

**Comment by ElgarL** [comment]
You used a reload plugin like Plugman. Plugman breaks many things. This is not a GroupManager issue.

**Comment by CyprusCraft** [comment]
I am not using plugin like plugman. I false one setting sync plugins on
tablist and it works. Thanks

Στις Τρί 27 Ιουν 2023, 02:13 ο χρήστης ElgarL ***@***.***>
έγραψε:
