### ISSUE TITLE
Error bei paper 1.20.2

### ISSUE THREAD

**Issue by BlackRed26** [ElgarL/GroupManager#103]
[23:20:27 INFO]: [GroupManager] Enabling GroupManager v3.2 (Phoenix)
[23:20:27 INFO]: [GroupManager] OfflinePlayers cached ( 7 ).
[23:20:27 ERROR]: [GroupManager] Missing or corrupt 'database' node. Using default settings
java.lang.IllegalArgumentException: The config.yml has no 'database'.
at org.anjocaido.groupmanager.GMConfiguration.getElement(GMConfiguration.java:331) ~[GroupManager.jar:?]
at org.anjocaido.groupmanager.GMConfiguration.load(GMConfiguration.java:197) ~[GroupManager.jar:?]
at org.anjocaido.groupmanager.GroupManager.onEnable(GroupManager.java:202) ~[GroupManager.jar:?]
at org.anjocaido.groupmanager.GroupManager.onEnable(GroupManager.java:151) ~[GroupManager.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-246]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-246]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644) ~[paper-1.20.2.jar:git-Paper-246]
at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555) ~[paper-1.20.2.jar:git-Paper-246]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-246]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-246]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-246]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-246]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-246]
at java.lang.Thread.run(Thread.java:840) ~[?:?]
&gt;
[23:20:27 ERROR]: [GroupManager] Missing or corrupt 'purge' node. Using default settings
java.lang.IllegalArgumentException: The config.yml has no 'maintenance'.
at org.anjocaido.groupmanager.GMConfiguration.getElement(GMConfiguration.java:331) ~[GroupManager.jar:?]
at org.anjocaido.groupmanager.GMConfiguration.load(GMConfiguration.java:268) ~[GroupManager.jar:?]
at org.anjocaido.groupmanager.GroupManager.onEnable(GroupManager.java:202) ~[GroupManager.jar:?]
at org.anjocaido.groupmanager.GroupManager.onEnable(GroupManager.java:151) ~[GroupManager.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-246]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-246]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644) ~[paper-1.20.2.jar:git-Paper-246]
at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555) ~[paper-1.20.2.jar:git-Paper-246]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-246]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-246]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-246]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-246]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-246]
at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by ElgarL** [comment]
Delete your config.yml
