### ISSUE TITLE
Error while disabling WG because "this.groupManager" is null?

### ISSUE THREAD

**Issue by Seasonull** [ElgarL/GroupManager#106]
Is this normal every time I shut down/restart? Does WG just not like GM? Or maybe I screwed up something when I first put the server together?

`13:26:54 ERROR]: Error occurred while disabling WorldGuard v7.0.12+829a4a4
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException: Cannot invoke "org.anjocaido.groupmanager.GroupManager.getWorldsHolder()" because "this.groupManager" is null
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2086) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:4012) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4035) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5013) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5020) ~[guava-32.1.2-jre.jar:?]
        at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.session.AbstractSessionManager.hasBypass(AbstractSessionManager.java:149) ~[worldguard-bukkit-7.0.12-dist.jar:?]
        at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.bukkit.session.BukkitSessionManager.hasBypass(BukkitSessionManager.java:86) ~[worldguard-bukkit-7.0.12-dist.jar:?]
        at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.session.handler.ExitFlag.onAbsentValue(ExitFlag.java:96) ~[worldguard-bukkit-7.0.12-dist.jar:?]
        at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.session.handler.ExitFlag.onAbsentValue(ExitFlag.java:33) ~[worldguard-bukkit-7.0.12-dist.jar:?]
        at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.session.handler.FlagValueChangeHandler.onClearValue(FlagValueChangeHandler.java:86) ~[worldguard-bukkit-7.0.12-dist.jar:?]
        at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.session.handler.FlagValueChangeHandler.uninitialize(FlagValueChangeHandler.java:50) ~[worldguard-bukkit-7.0.12-dist.jar:?]
        at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.session.Session.uninitialize(Session.java:144) ~[worldguard-bukkit-7.0.12-dist.jar:?]
        at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.bukkit.session.BukkitSessionManager.shutdown(BukkitSessionManager.java:92) ~[worldguard-bukkit-7.0.12-dist.jar:?]
        at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.bukkit.BukkitWorldGuardPlatform.unload(BukkitWorldGuardPlatform.java:149) ~[worldguard-bukkit-7.0.12-dist.jar:?]
        at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.WorldGuard.disable(WorldGuard.java:206) ~[worldguard-bukkit-7.0.12-dist.jar:?]
        at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.bukkit.WorldGuardPlugin.onDisable(WorldGuardPlugin.java:266) ~[worldguard-bukkit-7.0.12-dist.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:161) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:97) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:541) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.disablePlugins(CraftServer.java:609) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1045) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:847) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1351) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-89-1ed64f8]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.anjocaido.groupmanager.GroupManager.getWorldsHolder()" because "this.groupManager" is null
        at Vault.jar/net.milkbowl.vault.permission.plugins.Permission_GroupManager.playerHas(Permission_GroupManager.java:104) ~[Vault.jar:?]
        at Vault.jar/net.milkbowl.vault.permission.Permission.has(Permission.java:63) ~[Vault.jar:?]
        at Vault.jar/net.milkbowl.vault.permission.Permission.playerHas(Permission.java:132) ~[Vault.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.11.3-SNAPSHOT-917.jar/com.sk89q.wepif.VaultResolver.hasPermission(VaultResolver.java:102) ~[FastAsyncWorldEdit-Bukkit-2.11.3-SNAPSHOT-917.jar:?]
        at FastAsyncWorldEdit-Bukkit-2.11.3-SNAPSHOT-917.jar/com.sk89q.wepif.PermissionsResolverManager.hasPermission(PermissionsResolverManager.java:171) ~[FastAsyncWorldEdit-Bukkit-2.11.3-SNAPSHOT-917.jar:?]
        at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.bukkit.WorldGuardPlugin.hasPermission(WorldGuardPlugin.java:360) ~[worldguard-bukkit-7.0.12-dist.jar:?]
        at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.bukkit.BukkitPlayer.hasPermission(BukkitPlayer.java:219) ~[worldguard-bukkit-7.0.12-dist.jar:?]
        at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.session.AbstractSessionManager.lambda$static$0(AbstractSessionManager.java:63) ~[worldguard-bukkit-7.0.12-dist.jar:?]
        at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.session.AbstractSessionManager.lambda$new$1(AbstractSessionManager.java:69) ~[worldguard-bukkit-7.0.12-dist.jar:?]
        at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3571) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2313) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2190) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2080) ~[guava-32.1.2-jre.jar:?]
        ... 26 more`

**Comment by ElgarL** [comment]
Delete FAWE and see if it still happens.
WG should not be performing any permission checks through Vault upon shutdown. I can only assume there is some async task running in FAWE which is executing after GM has already terminated.
