### ISSUE TITLE
Not properly specifying duration can throw an uncatched ArrayOutOfBoundsException

### ISSUE THREAD

**Issue by l1ttleO** [ElgarL/GroupManager#46]
**Description**
See title

**Steps to reproduce**
1. Try running `/manuaddp <any user> essentials|` (permission doesn't matter here)

**Expected behavior**
The exception will be catched and the proper syntax will be displayed

**Screenshots**

**Please complete the following information:**
 - OS: Windows 10 2004
 - Paper/Spigot version: Tuinity 1.16.3
 - Plugin version: 2.9-SNAPSHOT

**Additional context**
Add any other context about the problem here, **including any error logs**.
```
[16:43:08] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 1
[16:43:08] [Server thread/WARN]: 	at org.anjocaido.groupmanager.commands.ManUAddSub.parseCommand(ManUAddSub.java:74)
[16:43:08] [Server thread/WARN]: 	at org.anjocaido.groupmanager.commands.BaseCommand.onCommand(BaseCommand.java:88)
[16:43:08] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[16:43:08] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[16:43:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802)
[16:43:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchServerCommand(CraftServer.java:764)
[16:43:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:406)
[16:43:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:373)
[16:43:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1267)
[16:43:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[16:43:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[16:43:08] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[16:43:08] [Server thread/INFO]: /manuaddsub <player> <group>
[16:43:28] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 1
[16:43:28] [Server thread/WARN]: 	at org.anjocaido.groupmanager.commands.ManUAddP.parseCommand(ManUAddP.java:88)
[16:43:28] [Server thread/WARN]: 	at org.anjocaido.groupmanager.commands.BaseCommand.onCommand(BaseCommand.java:88)
[16:43:28] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[16:43:28] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[16:43:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802)
[16:43:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchServerCommand(CraftServer.java:764)
[16:43:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:406)
[16:43:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:373)
[16:43:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1267)
[16:43:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[16:43:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[16:43:28] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[16:43:28] [Server thread/INFO]: /manuaddp <player> <permission> [permission2] [permission3]..
```

**Comment by ElgarL** [comment]
Fixed in  #https://github.com/ElgarL/GroupManager/commit/13db5d031c141ebc92c57ea6d2f26da269021e95
