### ISSUE TITLE
Unable to load GM jar file in 1.18.1 spigot with EssentialsX dev build. 

### ISSUE THREAD

**Issue by HaloArchive** [ElgarL/GroupManager#82]
Running spigot server 1.18.1 with EssentialsX 2.19.3 dev build on a linux docker. 

Download the file into plugins folder
curl -O https://github.com/ElgarL/GroupManager/releases/download/v2.9/GroupManager.jar

Start the server and get error stack:

[Server thread/ERROR]: Could not load 'plugins/GroupManager.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:144) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:415) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3385-Spigot-78a14d9-c93fcba]
at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:231) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3385-Spigot-78a14d9-c93fcba]
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:994) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3385-Spigot-78a14d9-c93fcba]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3385-Spigot-78a14d9-c93fcba]
at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.util.zip.ZipException: zip END header not found
at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469) ~[?:?]
at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477) ~[?:?]
at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315) ~[?:?]
at java.util.zip.ZipFile$Source.get(ZipFile.java:1277) ~[?:?]
at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709) ~[?:?]
at java.util.zip.ZipFile.<init>(ZipFile.java:243) ~[?:?]
at java.util.zip.ZipFile.<init>(ZipFile.java:172) ~[?:?]
at java.util.jar.JarFile.<init>(JarFile.java:347) ~[?:?]
at java.util.jar.JarFile.<init>(JarFile.java:318) ~[?:?]
at java.util.jar.JarFile.<init>(JarFile.java:284) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:166) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
... 6 more

**Comment by HaloArchive** [comment]
After looking into this, yes it was corrupt and failed silently. If anyone runs into this issue again, the redirect flag for curl needs to be set. The command changes into:

curl -O -L https://github.com/ElgarL/GroupManager/releases/download/v2.9/GroupManager.jar
