### ISSUE TITLE
An error was reported during loading

### ISSUE THREAD

**Issue by yuankun1** [ElgarL/GroupManager#91]
[06:06:59] [Server thread/ERROR]: Index: 0, Size: 0 initializing GroupManager v3.0-SNAPSHOT (Phoenix) (Is it up to date?)
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_333]
        at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_333]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.getOfflinePlayers(CraftServer.java:1537) ~[CraftServer.class:git-CatServer-1.12.2-8d58cdb8]
        at org.bukkit.Bukkit.getOfflinePlayers(Bukkit.java:847) ~[Bukkit.class:git-CatServer-1.12.2-8d58cdb8]
        at org.anjocaido.groupmanager.utils.OfflinePlayerCache.getInstance(OfflinePlayerCache.java:35) ~[?:?]
        at org.anjocaido.groupmanager.GroupManager.onLoad(GroupManager.java:132) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:364) [CraftServer.class:git-CatServer-1.12.2-8d58cdb8]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:340) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:330) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_333]

**Comment by ElgarL** [comment]
Interesting. This is an internal CatServer error with the OfflinePlayers.
Was this a restart or a startup? I'm going to need to know more about how this happened.

**Comment by yuankun1** [comment]
> Interesting. This is an internal CatServer error with the OfflinePlayers. Was this a restart or a startup? I'm going to need to know more about how this happened.

An error occurred when I started here

**Comment by ElgarL** [comment]
Try this jar (rename to jar from zip once downloaded.
[GroupManager.jar.zip](https://github.com/ElgarL/GroupManager/files/9541513/GroupManager.jar.zip)

**Comment by ElgarL** [comment]
I've pushed this fix to the current pre release so I'll close this ticket.
