### ISSUE TITLE
SQlite cannot be used

### ISSUE THREAD

**Issue by 3154311518** [ElgarL/GroupManager#97]
[23:24:53 INFO] [GroupManager] Enabling GroupManager v3.0-SNAPSHOT (Phoenix)
[23:24:53 INFO] [GroupManager] OfflinePlayers cached ( 1 ).
[23:24:53 WARN] SLF4J: No SLF4J providers were found.
[23:24:53 WARN] SLF4J: Defaulting to no-operation (NOP) logger implementation
[23:24:53 WARN] SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
[23:24:54 WARN] org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "ON":
 syntax error)
[23:24:54 WARN]         at org.sqlite.core.DB.newSQLException(DB.java:909)
[23:24:54 WARN]         at org.sqlite.core.DB.newSQLException(DB.java:921)
[23:24:54 WARN]         at org.sqlite.core.DB.throwex(DB.java:886)
[23:24:54 WARN]         at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[23:24:54 WARN]         at org.sqlite.core.NativeDB.prepare(NativeDB.java:127)
[23:24:54 WARN]         at org.sqlite.core.DB.prepare(DB.java:227)
[23:24:54 WARN]         at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:4
1)
[23:24:54 WARN]         at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.jav
a:30)
[23:24:54 WARN]         at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.jav
a:19)
[23:24:54 WARN]         at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:48
)
[23:24:54 WARN]         at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:26
3)
[23:24:54 WARN]         at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:23
5)
[23:24:54 WARN]         at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.j
ava:327)
[23:24:54 WARN]         at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxy
Connection.java)
[23:24:54 WARN]         at org.anjocaido.groupmanager.storage.CoreSQL.init(CoreSQL.java:118)
[23:24:54 WARN]         at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.loadParentWorld
s(WorldsHolder.java:136)
[23:24:54 WARN]         at org.anjocaido.groupmanager.dataholder.worlds.MirrorsMap.parseMirrors(Mirr
orsMap.java:97)
[23:24:54 WARN]         at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.initialLoad(Wor
ldsHolder.java:106)
[23:24:54 WARN]         at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.resetWorldsHold
er(WorldsHolder.java:95)
[23:24:54 WARN]         at org.anjocaido.groupmanager.GroupManager.onEnable(GroupManager.java:220)
[23:24:54 WARN]         at org.anjocaido.groupmanager.GroupManager.onEnable(GroupManager.java:151)
[23:24:54 WARN]         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[23:24:54 WARN]         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.jav
a:332)
[23:24:54 WARN]         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.ja
va:407)
[23:24:54 WARN]         at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:35
9)
[23:24:54 WARN]         at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java
:318)
[23:24:54 WARN]         at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:373)
[23:24:54 WARN]         at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:337)
[23:24:54 WARN]         at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[23:24:54 WARN]         at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:25
5)
[23:24:54 WARN]         at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528
)
[23:24:54 WARN]         at java.base/java.lang.Thread.run(Unknown Source)
[23:24:54 WARN] org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "ON":
 syntax error)
[23:24:54 WARN]         at org.sqlite.core.DB.newSQLException(DB.java:909)
[23:24:54 WARN]         at org.sqlite.core.DB.newSQLException(DB.java:921)
[23:24:54 WARN]         at org.sqlite.core.DB.throwex(DB.java:886)
[23:24:54 WARN]         at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[23:24:54 WARN]         at org.sqlite.core.NativeDB.prepare(NativeDB.java:127)
[23:24:54 WARN]         at org.sqlite.core.DB.prepare(DB.java:227)
[23:24:54 WARN]         at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:4
1)
[23:24:54 WARN]         at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.jav
a:30)
[23:24:54 WARN]         at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.jav
a:19)
[23:24:54 WARN]         at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:48
)
[23:24:54 WARN]         at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:26
3)
[23:24:54 WARN]         at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:23
5)
[23:24:54 WARN]         at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.j
ava:327)
[23:24:54 WARN]         at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxy
Connection.java)
[23:24:54 WARN]         at org.anjocaido.groupmanager.storage.CoreSQL.updateTableTimeStamp(CoreSQL.j
ava:1211)
[23:24:54 WARN]         at org.anjocaido.groupmanager.storage.CoreSQL.init(CoreSQL.java:133)
[23:24:54 WARN]         at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.loadParentWorld
s(WorldsHolder.java:136)
[23:24:54 WARN]         at org.anjocaido.groupmanager.dataholder.worlds.MirrorsMap.parseMirrors(Mirr
orsMap.java:97)
[23:24:54 WARN]         at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.initialLoad(Wor
ldsHolder.java:106)
[23:24:54 WARN]         at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.resetWorldsHold
er(WorldsHolder.java:95)
[23:24:54 WARN]         at org.anjocaido.groupmanager.GroupManager.onEnable(GroupManager.java:220)
[23:24:54 WARN]         at org.anjocaido.groupmanager.GroupManager.onEnable(GroupManager.java:151)
[23:24:54 WARN]         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[23:24:54 WARN]         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.jav
a:332)
[23:24:54 WARN]         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.ja
va:407)
[23:24:54 WARN]         at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:35
9)
[23:24:54 WARN]         at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java
:318)
[23:24:54 WARN]         at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:373)
[23:24:54 WARN]         at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:337)
[23:24:54 WARN]         at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[23:24:54 WARN]         at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:25
5)
[23:24:54 WARN]         at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528
)
[23:24:54 WARN]         at java.base/java.lang.Thread.run(Unknown Source)
[23:24:54 WARN] java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: There w
as no Default Group declared in file: world
[23:24:54 WARN]         at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source
)
[23:24:54 WARN]         at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
[23:24:54 WARN]         at org.anjocaido.groupmanager.storage.CoreSQL.loadGroups(CoreSQL.java:460)
[23:24:54 WARN]         at org.anjocaido.groupmanager.storage.CoreSQL.loadWorld(CoreSQL.java:382)
[23:24:54 WARN]         at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.loadParentWorld
s(WorldsHolder.java:137)
[23:24:54 WARN]         at org.anjocaido.groupmanager.dataholder.worlds.MirrorsMap.parseMirrors(Mirr
orsMap.java:97)
[23:24:54 WARN]         at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.initialLoad(Wor
ldsHolder.java:106)
[23:24:54 WARN]         at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.resetWorldsHold
er(WorldsHolder.java:95)
[23:24:54 WARN]         at org.anjocaido.groupmanager.GroupManager.onEnable(GroupManager.java:220)
[23:24:54 WARN]         at org.anjocaido.groupmanager.GroupManager.onEnable(GroupManager.java:151)
[23:24:54 WARN]         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[23:24:54 WARN]         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.jav
a:332)
[23:24:54 WARN]         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.ja
va:407)
[23:24:54 WARN]         at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:35
9)
[23:24:54 WARN]         at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java
:318)
[23:24:54 WARN]         at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:373)
[23:24:54 WARN]         at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:337)
[23:24:54 WARN]         at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[23:24:54 WARN]         at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:25
5)
[23:24:54 WARN]         at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528
)
[23:24:54 WARN]         at java.base/java.lang.Thread.run(Unknown Source)
[23:24:54 WARN] Caused by:
[23:24:54 WARN] java.lang.IllegalArgumentException: There was no Default Group declared in file: wor
ld
[23:24:54 WARN]         at org.anjocaido.groupmanager.storage.CoreSQL.lambda$loadGroupsAsync$10(Core
SQL.java:571)
[23:24:54 WARN]         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown
Source)
[23:24:54 WARN]         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown
 Source)
[23:24:54 WARN]         at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[23:24:54 WARN]         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknow
n Source)
[23:24:54 WARN]         at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
[23:24:54 WARN]         at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[23:24:54 WARN]         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[23:24:54 INFO] World Found: world
[23:24:54 INFO] Superperms support enabled.
[23:24:54 INFO] Scheduled Data Saving is set for every 10 minutes!
[23:24:54 INFO] Backups will be retained for 24 hours!
[23:24:54 INFO] DataSource - SQLITE
[23:24:54 INFO] version 3.0-SNAPSHOT (Phoenix) is enabled!
[23:24:54 INFO] Server permissions file permissions.yml is empty, ignoring it
[23:24:54 INFO] Done (1.431s)! For help, type "help" or "?"

**Comment by ElgarL** [comment]
Update to Java 11.

**Comment by ElgarL** [comment]
Ah yes, I didn't add SQLite support on pre 1.14 as it's not bundled in spigot. It was too large a dependency to include.
there should be a Libs folder on yoru server now. Drop an SQLite driver in there.

**Comment by ElgarL** [comment]
Try <https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/3.39.4.0/sqlite-jdbc-3.39.4.0.jar>

**Comment by ElgarL** [comment]
I remember now why I didn't support SQLite on versions prior to 1.14. It's because the driver in Spigot is too old and doesn't get overridden by libs.
Your error however is something related to your config.

**Comment by ElgarL** [comment]
Is there any specific reason you need SQLite as a database? H2 has the same operability in a single file system.

**Comment by ElgarL** [comment]
Unless you need something specific from SQL you should really stick with YAML.
SQLite and H2 database types save to a local file so are not really useful as SQL unless you have a specific requirement.
MYSQL is the most common, but for that you require an SQL server to host your database.
SQLite is not supported prior to 1.14 due to the driver supported by Spigot.

**Comment by ElgarL** [comment]
SQLite is only supported on 1.14+
