### ISSUE TITLE
manuaddp (temporairly permission) does not revoke

### ISSUE THREAD

**Issue by meganizer** [ElgarL/GroupManager#98]
**Description**
(I have added a temporarily permission to one of my players and on expiry the permission stays valid)

**Steps to reproduce**
1. Go to 'ingame having OP permission'
2. assign permission in my case (manuaddp playername essentials.protect.exemptbreak|1m)
3. Wait 2 minutes to expire the permission
4. Player can still break blacklisted blocks in my case

**Expected behavior**
(After step 3. Wait 2 minutes, the player should not be able to use the exempt permission and therefor cannot break the object)

**Please complete the following information:**
 - OS: Server runs on Ubuntu 22.04 in Pterodactyl container client runs on windows10 and windows11 for other player
 - Paper/Spigot version: This server is running CraftBukkit version 3604-Spigot-1aec3fc-f43634a (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT)
 - Plugin version [GroupManager] Loading GroupManager v2.9 (Phoenix)

**Additional context**
Here is the server log containing what happend with playernames replaced by random names

[22:46:45] [Server thread/INFO]: adminplayer issued server command: /manuaddp nonadminplayer essentials.protect.exemptbreak|1m
[22:46:45] [Server thread/INFO]: [GroupManager] Timed: essentials.protect.exemptbreak - expires: 14414367421
[22:47:50] [pool-9-thread-2/INFO]: [GroupManager] Timed Permission removed from : nonadminplayer : essentials.protect.exemptbreak
[22:47:50] [pool-9-thread-2/WARN]: [GroupManager] PlayerCommandSendEvent cannot be triggered asynchronously from another thread.
[22:48:22] [Server thread/INFO]: adminplayer issued server command: /manulistp nonadminplayer
[22:54:50] [pool-9-thread-1/INFO]: [GroupManager] Data files refreshed.

Here is the outcome of what the last command did (manulistp)

[00:48:24] [Render thread/INFO]: [System] [CHAT] The player 'nonadminplayer' has the following permissions:  essentials.protect.alerts.notrigger, essentials.protect.exemptusage
[00:48:24] [Render thread/INFO]: [System] [CHAT] And all permissions from groups: Moderator

The permission in question is not found in the group Moderator or in any globalgroups Moderator is attached to

**Comment by meganizer** [comment]
After further testing after a manload after the expiration the player in question can no longer break it but manload has to be manually triggered defeating the timer used in temporarily permissions

**Comment by ElgarL** [comment]
Can you test this with the 3.0-SNAPSHOT? (delete your config before starting server).
http://palmergames.com/libs/GroupManager.jar

**Comment by meganizer** [comment]
After testing with both versions I have some more logs entries

First for version 2.9

(server side)

[12:57:53] [Server thread/INFO]: adminplayer issued server command: /manuaddp nonadminplayer essentials.protect.exemptbreak|1m
[12:57:53] [Server thread/INFO]: [GroupManager] Timed: essentials.protect.exemptbreak - expires: 14414533215
[12:59:34] [pool-38-thread-1/INFO]: [GroupManager] Timed Permission removed from : nonadminplayer : essentials.protect.exemptbreak
[12:59:34] [pool-38-thread-1/WARN]: [GroupManager] PlayerCommandSendEvent cannot be triggered asynchronously from another thread.
[12:59:54] [Server thread/INFO]: adminplayer issued server command: /manucheckp nonadminplayer essentials.protect.exemptbreak
[13:01:27] [Server thread/INFO]: adminplayer issued server command: /manload
[13:01:27] [Server thread/WARN]: [GroupManager] Scheduled Data Saving is Disabled!
[13:01:27] [Server thread/INFO]: [GroupManager] version 2.9 (Phoenix) is disabled!
[13:01:27] [Server thread/WARN]: [GroupManager] Missing or corrupt 'tab_validate' node. Using default settings
[13:01:27] [Server thread/INFO]: [GroupManager] World Found: world
[13:01:27] [Server thread/INFO]: [GroupManager] Scheduled Data Saving is set for every 10 minutes!
[13:01:27] [Server thread/INFO]: [GroupManager] Backups will be retained for 24 hours!
[13:01:27] [Server thread/INFO]: [GroupManager] version 2.9 (Phoenix) is enabled!
[13:01:27] [Server thread/INFO]: [GroupManager] Bukkit Permissions Updated!
[13:01:27] [Craft Scheduler Thread - 8/INFO]: [GroupManager] There was an issue parsing the version string.
[13:01:27] [Craft Scheduler Thread - 8/INFO]: [GroupManager] No new version available
[13:01:29] [Server thread/INFO]: adminplayer issued server command: /manucheckp nonadminplayer essentials.protect.exemptbreak
[13:02:15] [Server thread/INFO]: adminplayer issued server command: /manuaddp nonadminplayer essentials.protect.exemptbreak|1m
[13:02:15] [Server thread/INFO]: [GroupManager] Timed: essentials.protect.exemptbreak - expires: 14414533623
[13:02:18] [Server thread/INFO]: adminplayer issued server command: /manucheckp nonadminplayer essentials.protect.exemptbreak
[13:03:27] [pool-39-thread-1/INFO]: [GroupManager] Timed Permission removed from : nonadminplayer : essentials.protect.exemptbreak
[13:03:27] [pool-39-thread-1/WARN]: [GroupManager] PlayerCommandSendEvent cannot be triggered asynchronously from another thread.

(client side)

[14:57:53] [Render thread/INFO]: [System] [CHAT] You added 'essentials.protect.exemptbreak' to user 'nonadminplayer' permissions with a duration of 1 minutes.
[14:59:53] [Render thread/INFO]: [System] [CHAT] The user doesn't have access to that permission.
[14:59:53] [Render thread/INFO]: [System] [CHAT] SuperPerms reports Node: true
[15:01:26] [Render thread/INFO]: [System] [CHAT] All settings and worlds were reloaded!
[15:01:29] [Render thread/INFO]: [System] [CHAT] The user doesn't have access to that permission.
[15:01:29] [Render thread/INFO]: [System] [CHAT] SuperPerms reports Node: false
[15:02:15] [Render thread/INFO]: [System] [CHAT] You added 'essentials.protect.exemptbreak' to user 'nonadminplayer' permissions with a duration of 1 minutes.
[15:02:18] [Render thread/INFO]: [System] [CHAT] The user directly has this permission.
[15:02:18] [Render thread/INFO]: [System] [CHAT] Permission Node: essentials.protect.exemptbreak
[15:02:18] [Render thread/INFO]: [System] [CHAT] SuperPerms reports Node: true

Now for version 3.0-SNAPSHOT

(server side)

[13:07:23] [Server thread/INFO]: adminplayer issued server command: /manuaddp nonadminplayer essentials.protect.exemptbreak|1m
[13:07:50] [Server thread/INFO]: adminplayer issued server command: /manucheckp nonadminplayer essentials.protect.exemptbreak
[13:08:27] [pool-10-thread-1/INFO]: Timed Permission removed from : nonadminplayer : essentials.protect.exemptbreak
[13:08:27] [pool-10-thread-1/ERROR]: Failed to purge expired permissions: null
[13:08:56] [Server thread/INFO]: adminplayer issued server command: /manucheckp nonadminplayer essentials.protect.exemptbreak
[13:09:04] [Server thread/INFO]: adminplayer issued server command: /manload
[13:09:04] [Server thread/WARN]: Scheduled Data Saving is Disabled!
[13:09:04] [Server thread/INFO]: version 3.0-SNAPSHOT (Phoenix) is disabled!
[13:09:04] [Server thread/INFO]: World Found: world
[13:09:04] [Server thread/INFO]: Scheduled Data Saving is set for every 10 minutes!
[13:09:04] [Server thread/INFO]: Backups will be retained for 24 hours!
[13:09:04] [Server thread/INFO]: DataSource - YAML
[13:09:04] [Server thread/INFO]: version 3.0-SNAPSHOT (Phoenix) is enabled!
[13:09:04] [Server thread/INFO]: Bukkit Permissions Updated!
[13:09:04] [Craft Scheduler Thread - 5/INFO]: No new version available
[13:09:12] [Server thread/INFO]: adminplayer issued server command: /manucheckp nonadminplayer essentials.protect.exemptbreak
[13:10:04] [pool-39-thread-3/INFO]: Timed Permission removed from : nonadminplayer : essentials.protect.exemptbreak
[13:10:04] [pool-39-thread-3/ERROR]: Failed to purge expired permissions: null
[13:10:21] [Server thread/INFO]: adminplayer issued server command: /manucheckp nonadminplayer essentials.protect.exemptbreak

(client side)

[15:07:23] [Render thread/INFO]: [System] [CHAT] You added 'essentials.protect.exemptbreak' to user 'nonadminplayer' permissions with a duration of 1 minutes.
[15:07:50] [Render thread/INFO]: [System] [CHAT] The user directly has this permission.
[15:07:50] [Render thread/INFO]: [System] [CHAT] Permission Node: essentials.protect.exemptbreak
[15:07:50] [Render thread/INFO]: [System] [CHAT] SuperPerms reports Node: true
[15:08:56] [Render thread/INFO]: [System] [CHAT] The user doesn't have access to that permission.
[15:08:56] [Render thread/INFO]: [System] [CHAT] SuperPerms reports Node: true
[15:09:04] [Render thread/INFO]: [System] [CHAT] All settings and worlds were reloaded!
[15:09:12] [Render thread/INFO]: [System] [CHAT] The user directly has this permission.
[15:09:12] [Render thread/INFO]: [System] [CHAT] Permission Node: essentials.protect.exemptbreak
[15:09:12] [Render thread/INFO]: [System] [CHAT] SuperPerms reports Node: true
[15:10:20] [Render thread/INFO]: [System] [CHAT] The user doesn't have access to that permission.
[15:10:20] [Render thread/INFO]: [System] [CHAT] SuperPerms reports Node: true

**Comment by ElgarL** [comment]
I'm not seeing the same results.

[14:31:27] [Server thread/INFO]: Made ElgarL no longer a server operator
/manucheckp ElgarL test.perm
[14:31:34] [Server thread/INFO]: The user doesn't have access to that permission.
[14:31:34] [Server thread/INFO]: SuperPerms reports Node: false
/manuaddp ElgarL test.perm|1m
[14:31:41] [Server thread/INFO]: You added 'test.perm' to user 'ElgarL' permissions with a duration of 1 minutes.
/manucheckp ElgarL test.perm
[14:32:50] [Server thread/INFO]: The user directly has this permission.
[14:32:50] [Server thread/INFO]: Permission Node: test.perm
[14:32:50] [Server thread/INFO]: SuperPerms reports Node: true
[14:32:56] [pool-8-thread-3/INFO]: Timed Permission removed from : ElgarL : test.perm
/manucheckp ElgarL test.perm
[14:33:02] [Server thread/INFO]: The user doesn't have access to that permission.
[14:33:02] [Server thread/INFO]: SuperPerms reports Node: false

**Comment by meganizer** [comment]
I can also verify that the players do not have op

`>manulistp tuinkabouter1996
[17:41:33] [Server thread/INFO]: The player 'Tuinkabouter1996' has the following permissions: essentials.lightning, essentials.protect.alerts.notrigger, essentials.protect.exemptusage, worldedit.history.undo.self, worldedit.navigation.*, worldedit.region.replace, worldedit.region.set
[17:41:33] [Server thread/INFO]: And all permissions from groups: Moderator
>manudel tuinkabouter1996
[17:41:53] [Server thread/INFO]: You changed player 'Tuinkabouter1996' to default settings.
>deop tuinkabouter1996
[17:41:57] [Server thread/INFO]: Nothing changed. The player is not an operator
>manuadd tuinkabouter1996 moderator
[17:42:06] [Server thread/INFO]: You changed player 'Tuinkabouter1996' group to 'Moderator' in world 'world'.
>manuaddp tuinkabouter1996 essentials.protect.exemptbreak|1m
[17:42:24] [Server thread/INFO]: You added 'essentials.protect.exemptbreak' to user 'Tuinkabouter1996' permissions with a duration of 1 minutes.
>manucheckp tuinkabouter1996 essentials.protect.exemptbreak
[17:42:39] [Server thread/INFO]: The user directly has this permission.
[17:42:39] [Server thread/INFO]: Permission Node: essentials.protect.exemptbreak
[17:42:39] [Server thread/INFO]: SuperPerms reports Node: true
[17:43:44] [pool-9-thread-2/INFO]: Timed Permission removed from : Tuinkabouter1996 : essentials.protect.exemptbreak
>manucheckp tuinkabouter1996 essentials.protect.exemptbreak
[17:44:02] [Server thread/INFO]: The user doesn't have access to that permission.
[17:44:02] [Server thread/INFO]: SuperPerms reports Node: false
>manuaddp tuinkabouter1996 essentials.lightning
[17:44:22] [Server thread/INFO]: You added 'essentials.lightning' to user 'Tuinkabouter1996' permissions.
>manuaddp tuinkabouter1996 essentials.protect.alerts.notrigger
[17:44:32] [Server thread/INFO]: You added 'essentials.protect.alerts.notrigger' to user 'Tuinkabouter1996' permissions.
>manuaddp tuinkabouter1996 essentials.protect.exemptusage
[17:44:39] [Server thread/INFO]: You added 'essentials.protect.exemptusage' to user 'Tuinkabouter1996' permissions.
>manuaddp tuinkabouter1996 worldedit.history.undo.self
[17:44:51] [Server thread/INFO]: You added 'worldedit.history.undo.self' to user 'Tuinkabouter1996' permissions.
>manuaddp tuinkabouter1996 worldedit.navigation.*
[17:44:59] [Server thread/INFO]: You added 'worldedit.navigation.*' to user 'Tuinkabouter1996' permissions.
>manuaddp tuinkabouter1996 worldedit.region.replace
[17:45:05] [Server thread/INFO]: You added 'worldedit.region.replace' to user 'Tuinkabouter1996' permissions.
>manuaddp tuinkabouter1996 worldedit.region.set
[17:45:08] [Server thread/INFO]: You added 'worldedit.region.set' to user 'Tuinkabouter1996' permissions.
>manucheckp tuinkabouter1996 essentials.protect.exemptbreak
[17:45:21] [Server thread/INFO]: The user doesn't have access to that permission.
[17:45:21] [Server thread/INFO]: SuperPerms reports Node: false
>manuaddp tuinkabouter1996 essentials.protect.exemptbreak|1m
[17:45:37] [Server thread/INFO]: You added 'essentials.protect.exemptbreak' to user 'Tuinkabouter1996' permissions with a duration of 1 minutes.
>manucheckp tuinkabouter1996 essentials.protect.exemptbreak
[17:45:57] [Server thread/INFO]: The user directly has this permission.
[17:45:57] [Server thread/INFO]: Permission Node: essentials.protect.exemptbreak
[17:45:57] [Server thread/INFO]: SuperPerms reports Node: true
[17:46:44] [pool-9-thread-2/INFO]: Timed Permission removed from : Tuinkabouter1996 : essentials.protect.exemptbreak
[17:46:44] [pool-9-thread-2/ERROR]: Failed to purge expired permissions: null
>manucheckp tuinkabouter1996 essentials.protect.exemptbreak
[17:47:05] [Server thread/INFO]: The user doesn't have access to that permission.
[17:47:05] [Server thread/INFO]: SuperPerms reports Node: true
`

However with further testing i notice that when the user has permanent permissions the temporary will not revoke as seen in the log

**Comment by ElgarL** [comment]
I'm not sure what you are doing different to me but I can't make it fail.
![image](https://user-images.githubusercontent.com/898636/230788883-5248dece-cf32-4f27-9dc9-8392f28a413f.png)

**Comment by meganizer** [comment]
It gave alot more details

`>manudel meganizer
[18:13:20] [Server thread/INFO]: You changed player 'Meganizer' to default settings.
>deop meganizer
[18:13:23] [Server thread/INFO]: Nothing changed. The player is not an operator
>manuaddp meganizer temp.permanent
[18:13:38] [Server thread/INFO]: You added 'temp.permanent' to user 'Meganizer' permissions.
>manuaddp meganizer temp.perm|1m
[18:13:55] [Server thread/INFO]: You added 'temp.perm' to user 'Meganizer' permissions with a duration of 1 minutes.
>manucheckp meganizer temp.perm
[18:14:03] [Server thread/INFO]: The user directly has this permission.
[18:14:03] [Server thread/INFO]: Permission Node: temp.perm
[18:14:03] [Server thread/INFO]: SuperPerms reports Node: true
[18:15:25] [pool-9-thread-1/INFO]: Timed Permission removed from : Meganizer : temp.perm
[18:15:25] [pool-9-thread-1/ERROR]: Failed to purge expired permissions:
java.util.ConcurrentModificationException
        at java.base/java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486)
        at java.base/java.util.TreeMap$EntryIterator.next(TreeMap.java:1522)
        at java.base/java.util.TreeMap$EntryIterator.next(TreeMap.java:1517)
        at org.anjocaido.groupmanager.data.DataUnit.removeExpired(DataUnit.java:318)
        at org.anjocaido.groupmanager.data.User.removeExpired(User.java:491)
        at org.anjocaido.groupmanager.dataholder.WorldDataHolder.purgeTimedPermissions(WorldDataHolder.java:515)
        at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.purgeExpiredPerms(WorldsHolder.java:204)
        at org.anjocaido.groupmanager.GroupManager.lambda$enableScheduler$3(GroupManager.java:435)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
>manucheckp meganizer temp.perm
[18:15:45] [Server thread/INFO]: The user doesn't have access to that permission.
[18:15:45] [Server thread/INFO]: SuperPerms reports Node: true`

**Comment by ElgarL** [comment]
Grab a new copy and try again.

**Comment by meganizer** [comment]
Seems to work now :)

`>manudel meganizer
[18:36:03] [Server thread/INFO]: You changed player 'Meganizer' to default settings.
>deop meganizer
[18:36:07] [Server thread/INFO]: Nothing changed. The player is not an operator
>manuaddp meganizer perm.permanent
[18:36:21] [Server thread/INFO]: You added 'perm.permanent' to user 'Meganizer' permissions.
>manuaddp meganizer perm.temp|1m
[18:36:32] [Server thread/INFO]: You added 'perm.temp' to user 'Meganizer' permissions with a duration of 1 minutes.
>manucheckp meganizer perm.temp
[18:36:39] [Server thread/INFO]: The user directly has this permission.
[18:36:39] [Server thread/INFO]: Permission Node: perm.temp
[18:36:39] [Server thread/INFO]: SuperPerms reports Node: true
[18:38:30] [pool-9-thread-1/INFO]: Timed Permission removed from : Meganizer : perm.temp
>manucheckp meganizer perm.temp
[18:38:45] [Server thread/INFO]: The user doesn't have access to that permission.
[18:38:45] [Server thread/INFO]: SuperPerms reports Node: false`

**Comment by ElgarL** [comment]
I have a few other places I need to implement that fix so I'll close this when done.

**Comment by ElgarL** [comment]
Final fix is @ http://palmergames.com/libs/GroupManager.jar

**Comment by meganizer** [comment]
There is still a small error in the final fix, 

Whenever we add another permission that looks like the temporary it still stays true again

`>manudel tuinkabouter1996
[18:56:19] [Server thread/INFO]: You changed player 'Tuinkabouter1996' to default settings.
>deop tuinkabouter1996
[18:56:23] [Server thread/INFO]: Nothing changed. The player is not an operator
>manuaddp tuinkabouter1996 worldedit.region.set
[18:56:51] [Server thread/INFO]: You added 'worldedit.region.set' to user 'Tuinkabouter1996' permissions.
[18:57:17] [Server thread/INFO]: Tuinkabouter1996 issued server command: //set sand
>manuaddp tuinkabouter1996 essentials.protect.exemptbreak|1m
[18:57:53] [Server thread/INFO]: You added 'essentials.protect.exemptbreak' to user 'Tuinkabouter1996' permissions with a duration of 1 minutes.
>manucheckp tuinkabouter1996 essentials.protect.exemptbreak
[18:58:05] [Server thread/INFO]: The user directly has this permission.
[18:58:05] [Server thread/INFO]: Permission Node: essentials.protect.exemptbreak
[18:58:05] [Server thread/INFO]: SuperPerms reports Node: true
[18:58:15] [Server thread/WARN]: §3[Tuinkabouter1996] §r broke: §6 barrier at: world,1168,65,-1214
[18:59:06] [pool-9-thread-1/INFO]: Timed Permission removed from : Tuinkabouter1996 : essentials.protect.exemptbreak
>manucheckp tuinkabouter1996 essentials.protect.exemptbreak
[18:59:24] [Server thread/INFO]: The user doesn't have access to that permission.
[18:59:24] [Server thread/INFO]: SuperPerms reports Node: false
>manuaddp tuinkabouter1996 essentials.protect.exemptusage
[19:00:57] [Server thread/INFO]: You added 'essentials.protect.exemptusage' to user 'Tuinkabouter1996' permissions.
>manucheckp tuinkabouter1996 essentials.protect.exemptbreak
[19:01:19] [Server thread/INFO]: The user doesn't have access to that permission.
[19:01:19] [Server thread/INFO]: SuperPerms reports Node: false
>manuaddp tuinkabouter1996 essentials.protect.exemptbreak|1m
[19:01:43] [Server thread/INFO]: You added 'essentials.protect.exemptbreak' to user 'Tuinkabouter1996' permissions with a duration of 1 minutes.
>manucheckp tuinkabouter1996 essentials.protect.exemptbreak
[19:01:53] [Server thread/INFO]: The user directly has this permission.
[19:01:53] [Server thread/INFO]: Permission Node: essentials.protect.exemptbreak
[19:01:53] [Server thread/INFO]: SuperPerms reports Node: true
[19:01:58] [Server thread/WARN]: §3[Tuinkabouter1996] §r broke: §6 barrier at: world,1168,65,-1215
[19:03:06] [pool-9-thread-2/INFO]: Timed Permission removed from : Tuinkabouter1996 : essentials.protect.exemptbreak
>manucheckp tuinkabouter1996 essentials.protect.exemptbreak
[19:03:17] [Server thread/INFO]: The user doesn't have access to that permission.
[19:03:17] [Server thread/INFO]: SuperPerms reports Node: true`

**Comment by ElgarL** [comment]
I'm not sure what you are doing here to have it removed yet show true in superperms.

**Comment by meganizer** [comment]
It seems to happen alot with the permission nodes of the plugin EssentialsX 
For example to two i used here (essentials.protect.exemptbreak)(essentials.protect.exemptusage)
The adding and players are randomly chosen in this testing scenario,
The server already has a sandbox copy where we test this on I can also add another account to the admin dashboard of the server so you can see for yourself

**Comment by ElgarL** [comment]
I just need a reliable way to replicate to test here.

**Comment by meganizer** [comment]
We gained our server.jar here version 1.19.2 release date Friday, August 05 2022
[https://getbukkit.org/download/spigot](url)

The plugins that we use are 
![plugins](https://user-images.githubusercontent.com/77209206/230792431-57c3d34f-b1a1-4841-b0b4-1e893ded6ab9.png)

and after launch we just use the manuaddp username permission|time command

**Comment by ElgarL** [comment]
Grab a new jar, it should be fixed now.

**Comment by meganizer** [comment]
Still gives an error in the console but the permission is false the fix works this time even with all of the permissions we use

`>manulistp tuinkabouter1996
[20:23:09] [Server thread/INFO]: The player 'Tuinkabouter1996' has the following permissions: essentials.protect.exemptusage, worldedit.region.set
[20:23:09] [Server thread/INFO]: And all permissions from groups: Default
>deop tuinkabouter1996
[20:23:14] [Server thread/INFO]: Nothing changed. The player is not an operator
>manuaddp tuinkabouter1996 essentials.protect.exemptbreak|1m
[20:23:33] [Server thread/INFO]: You added 'essentials.protect.exemptbreak' to user 'Tuinkabouter1996' permissions with a duration of 1 minutes.
[20:23:48] [Server thread/WARN]: §3[Tuinkabouter1996] §r broke: §6 barrier at: world,1168,66,-1213
>manucheckp tuinkabouter1996 essentials.protect.exemptbreak
[20:24:14] [Server thread/INFO]: The user directly has this permission.
[20:24:14] [Server thread/INFO]: Permission Node: essentials.protect.exemptbreak
[20:24:14] [Server thread/INFO]: SuperPerms reports Node: true
[20:25:14] [pool-9-thread-1/INFO]: Timed Permission removed from : Tuinkabouter1996 : essentials.protect.exemptbreak
>manucheckp tuinkabouter1996 essentials.protect.exemptbreak
[20:25:30] [Server thread/INFO]: The user doesn't have access to that permission.
[20:25:30] [Server thread/INFO]: SuperPerms reports Node: false
>manudel tuinkabouter1996
[20:25:43] [Server thread/INFO]: You changed player 'Tuinkabouter1996' to default settings.
[20:26:01] [Server thread/INFO]: Meganizer issued server command: /manuadd Tuinkabouter1996 Moderator
[20:26:23] [Server thread/INFO]: Meganizer issued server command: /manuaddp Tuinkabouter1996 essentials.lightning
[20:26:34] [Server thread/INFO]: Meganizer issued server command: /manuaddp Tuinkabouter1996 essentials.protect.alerts.notrigger
[20:26:47] [Server thread/INFO]: Meganizer issued server command: /manuaddp Tuinkabouter1996 essentials.protect.exemptusage
[20:27:01] [Server thread/INFO]: Meganizer issued server command: /manuaddp Tuinkabouter1996 worldedit.history.undo.self
[20:27:08] [Server thread/INFO]: Meganizer issued server command: /manuaddp Tuinkabouter1996 worldedit.navigation.*
[20:27:15] [Server thread/INFO]: Meganizer issued server command: /manuaddp Tuinkabouter1996 worldedit.region.replace
[20:27:20] [Server thread/INFO]: Meganizer issued server command: /manuaddp Tuinkabouter1996 worldedit.region.set
>manucheckp tuinkabouter1996 essentials.protect.exemptbreak
[20:27:58] [Server thread/INFO]: The user doesn't have access to that permission.
[20:27:58] [Server thread/INFO]: SuperPerms reports Node: false
>manuaddp tuinkabouter1996 essentials.protect.exemptbreak|1m
[20:28:10] [Server thread/INFO]: You added 'essentials.protect.exemptbreak' to user 'Tuinkabouter1996' permissions with a duration of 1 minutes.
>manucheckp tuinkabouter1996 essentials.protect.exemptbreak
[20:28:24] [Server thread/INFO]: The user directly has this permission.
[20:28:24] [Server thread/INFO]: Permission Node: essentials.protect.exemptbreak
[20:28:24] [Server thread/INFO]: SuperPerms reports Node: true
[20:29:14] [pool-9-thread-2/INFO]: Timed Permission removed from : Tuinkabouter1996 : essentials.protect.exemptbreak
[20:29:14] [Server thread/WARN]: [GroupManager] Task #1568 for GroupManager v3.0-SNAPSHOT (Phoenix) generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.permissions.PermissionAttachmentInfo.getValue()" because the return value of "java.util.Map.get(Object)" is null
        at org.bukkit.permissions.PermissibleBase.hasPermission(PermissibleBase.java:76) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:193) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
        at org.bukkit.command.Command.testPermissionSilent(Command.java:213) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.test(BukkitCommandWrapper.java:42) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.test(BukkitCommandWrapper.java:1) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:79) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:401) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:374) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.updateCommands(CraftPlayer.java:1930) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1245) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:394) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1197) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1013) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
        at java.lang.Thread.run(Thread.java:833) [?:?]
>manucheckp tuinkabouter1996 essentials.protect.exemptbreak
[20:29:39] [Server thread/INFO]: The user doesn't have access to that permission.
[20:29:39] [Server thread/INFO]: SuperPerms reports Node: false
`

**Comment by ElgarL** [comment]
Interesting error. It's all in Minecraft/Bukkit. No plugin mentioned in the stacktrace.

**Comment by ElgarL** [comment]
I can't replicate that error so I'll close this for now but post if it happens again.
